"""
Thin HTTP surface over the classification core (engine.classify).

This is NOT a separate backend service — it's a lightweight FastAPI wrapper that
reuses the exact same detection pipeline the mitmproxy addon calls in-process, so
the browser extension and dashboard get identical verdicts. /logs and /stats
arrive with the SQLite logger in a later task.

Run:  uvicorn api:app --port 8000     (or: python -m uvicorn api:app)
"""
from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import os
import re
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env", override=True)

import httpx
import engine
import redactor
import logger

logger.init_db()

app = FastAPI(title="AI DLP — Classification API")

# The extension and dashboard call this from other origins; open CORS for the demo.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ClassifyRequest(BaseModel):
    text: str
    source: str = "extension"
    session_id: str = "default"
    context: list[str] = []


class RedactAndAskRequest(BaseModel):
    prompt: str


def simulate_llm_response(prompt: str) -> str:
    # Find all placeholders in the prompt, e.g. [REDACTED_NAME_1] or [NAME_1]
    placeholders = re.findall(r"(\[[A-Z0-9_]+\])", prompt)
    if placeholders:
        unique_placeholders = sorted(list(set(placeholders)))
        ph_list = ", ".join(unique_placeholders)
        return (
            f"Hello! I am a simulated cloud model. I received the following prompt from you:\n\n"
            f"\"{prompt}\"\n\n"
            f"I detected the following sanitized placeholders: {ph_list}.\n\n"
            f"Because this is a demo environment, I will echo back a mock answer containing your placeholders. "
            f"Normally, this response is generated by a cloud LLM (which only sees the placeholders), "
            f"and then the CLOAKWELL local-first layer swaps the real values back in before you see it.\n\n"
            f"Here is a mock response: 'Dear customer {ph_list}, thank you for contacting us. We have processed your request. Let us know if we can help you further!'"
        )
    else:
        return (
            f"Hello! I am a simulated cloud model. Because your prompt did not contain any sensitive PII, "
            f"no redaction was needed, and the prompt was forwarded directly as-is.\n\n"
            f"Prompt: \"{prompt}\"\n\n"
            f"Response: I have processed your request! Please let me know how else I can help you."
        )


def query_local_gemma(prompt: str) -> str:
    """Send prompt locally to Google Gemma 2 running on the AMD Instinct GPU."""
    base_url = os.getenv("FIREWORKS_BASE_URL", "http://localhost:11434/v1")
    model = os.getenv("FIREWORKS_MODEL", "google/gemma-2-2b-it")
    try:
        from openai import OpenAI
        client = OpenAI(
            api_key="local-ollama",
            base_url=base_url
        )
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=1024,
        )
        return resp.choices[0].message.content
    except Exception as e:
        return f"[Failed to query local Gemma 2 on AMD GPU: {e}]"


def query_fireworks_deepseek(prompt: str) -> str:
    """Send prompt to the Fireworks serverless DeepSeek model."""
    api_key = os.getenv("FIREWORKS_API_KEY", "")
    if not api_key or api_key == "local-ollama" or "<PLACE_YOUR_FIREWORKS_API_KEY_HERE>" in api_key:
        return simulate_llm_response(prompt)
    try:
        from openai import OpenAI
        client = OpenAI(
            api_key=api_key,
            base_url="https://api.fireworks.ai/inference/v1"
        )
        cloud_model = os.getenv("CLOUD_LLM_MODEL", "accounts/fireworks/models/deepseek-v4-pro")
        resp = client.chat.completions.create(
            model=cloud_model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=1024,
        )
        return resp.choices[0].message.content
    except Exception as e:
        return f"[Fireworks DeepSeek query failed: {e}. Falling back to simulation]\n\n" + simulate_llm_response(prompt)



@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/api/classify")
def classify(req: ClassifyRequest):
    return engine.classify(
        req.text,
        session_id=req.session_id,
        source=req.source,
        context=req.context or None,
    )


@app.post("/redact-and-ask")
def redact_and_ask(req: RedactAndAskRequest):
    # 1. Classify prompt using the core engine (Tier 1 regex + Tier 2 local Gemma 2)
    classification = engine.classify(req.prompt)
    label = classification["label"]
    
    # 2. Routing based on presence of sensitive PII / terms
    if label in ("BLOCK", "ACTION_NEEDED", "WARN"):
        # Contains sensitive data -> Bypasses public cloud completely. Handled locally on private AMD GPU.
        response = query_local_gemma(req.prompt)
        final_response = "🤖 **[Secure Local Mode: Response generated by Google Gemma-2-2B-it on private AMD Instinct GPU due to sensitive data/PII]**\n\n" + response
        
        return {
            "final_response": final_response,
            "redacted_text": "🔒 [Zero Data Egress] This query was blocked from leaving your network and routed locally to your private AMD Instinct GPU.",
            "entities_detected": classification["entities"]
        }
        
    else:  # INFO
        # Benign prompt -> Send directly to DeepSeek on Fireworks Cloud
        cloud_response = query_fireworks_deepseek(req.prompt)
        final_response = "☁️ **[Standard Cloud Mode: Response generated by DeepSeek-V4-Pro on Fireworks Cloud]**\n\n" + cloud_response
        
        return {
            "final_response": final_response,
            "redacted_text": req.prompt,
            "entities_detected": []
        }


@app.get("/api/logs")
def get_logs(limit: int = 50, offset: int = 0, label: str | None = None):
    return logger.get_logs(limit=limit, offset=offset, label_filter=label)


@app.get("/api/stats")
def get_stats():
    return logger.get_stats()


from fastapi.staticfiles import StaticFiles

# Mount static files for the dashboard at the root URL
app.mount("/", StaticFiles(directory="../dashboard", html=True), name="static")


