"""
Thin HTTP surface over the classification core (engine.classify).

This is NOT a separate backend service — it's a lightweight FastAPI wrapper that
reuses the exact same detection pipeline the mitmproxy addon calls in-process, so
the browser extension and dashboard get identical verdicts. /logs and /stats
arrive with the SQLite logger in a later task.

Run:  uvicorn api:app --port 8000     (or: python -m uvicorn api:app)
"""
from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import os
import re
import httpx
import engine
import redactor

app = FastAPI(title="AI DLP — Classification API")

# The extension and dashboard call this from other origins; open CORS for the demo.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


class ClassifyRequest(BaseModel):
    text: str
    source: str = "extension"
    session_id: str = "default"
    context: list[str] = []


class RedactAndAskRequest(BaseModel):
    prompt: str


def simulate_llm_response(prompt: str) -> str:
    # Find all placeholders in the prompt, e.g. [REDACTED_NAME_1] or [NAME_1]
    placeholders = re.findall(r"(\[[A-Z0-9_]+\])", prompt)
    if placeholders:
        unique_placeholders = sorted(list(set(placeholders)))
        ph_list = ", ".join(unique_placeholders)
        return (
            f"Hello! I am a simulated cloud model. I received the following prompt from you:\n\n"
            f"\"{prompt}\"\n\n"
            f"I detected the following sanitized placeholders: {ph_list}.\n\n"
            f"Because this is a demo environment, I will echo back a mock answer containing your placeholders. "
            f"Normally, this response is generated by a cloud LLM (which only sees the placeholders), "
            f"and then the CLOAKWELL local-first layer swaps the real values back in before you see it.\n\n"
            f"Here is a mock response: 'Dear customer {ph_list}, thank you for contacting us. We have processed your request. Let us know if we can help you further!'"
        )
    else:
        return (
            f"Hello! I am a simulated cloud model. Because your prompt did not contain any sensitive PII, "
            f"no redaction was needed, and the prompt was forwarded directly as-is.\n\n"
            f"Prompt: \"{prompt}\"\n\n"
            f"Response: I have processed your request! Please let me know how else I can help you."
        )


def query_cloud_llm(redacted_prompt: str) -> str:
    # Always use local simulation for demo stability and speed
    return simulate_llm_response(redacted_prompt)



@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/api/classify")
def classify(req: ClassifyRequest):
    return engine.classify(
        req.text,
        session_id=req.session_id,
        source=req.source,
        context=req.context or None,
    )


@app.post("/redact-and-ask")
def redact_and_ask(req: RedactAndAskRequest):
    # 1. Classify & Redact prompt using the core engine
    classification = engine.classify(req.prompt)
    
    # 2. Check if blocked
    if classification["label"] == "BLOCK":
        detected_types = [e.get("type", "SENSITIVE") for e in classification["entities"]]
        blocked_msg = f"Blocked by CLOAKWELL local-first security policy (detected: {', '.join(detected_types)})."
        return {
            "final_response": blocked_msg,
            "redacted_text": classification["redacted_text"],
            "entities_detected": classification["entities"]
        }
        
    # 3. Call the cloud LLM using the redacted prompt
    redacted_prompt = classification["redacted_text"]
    cloud_response = query_cloud_llm(redacted_prompt)
    
    # 4. Swap placeholders back to real values locally
    redirection_map = classification.get("redaction_map", {})
    final_response = redactor.unredact(cloud_response, redirection_map)
    
    return {
        "final_response": final_response,
        "redacted_text": redacted_prompt,
        "entities_detected": classification["entities"]
    }


from fastapi.staticfiles import StaticFiles

# Mount static files for the dashboard at the root URL
app.mount("/", StaticFiles(directory="../dashboard", html=True), name="static")


